# Generated by Django 4.1.1 on 2022-09-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_name",
                    models.CharField(
                        help_text="обязательное поле",
                        max_length=255,
                        verbose_name="название доставки",
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_length": "Стоимость должна быть в пределах от 0 до 9999.99"
                            }
                        },
                        help_text="Максимум 99999.99",
                        max_digits=7,
                        verbose_name="стоимость доставки",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("IS", "В магазин"),
                            ("INP", "В отделение Новой Почты"),
                            ("CD", "Доставка курьером"),
                        ],
                        help_text="обязательно",
                        max_length=255,
                        verbose_name="вариант доставки",
                    ),
                ),
                (
                    "delivery_timeframe",
                    models.CharField(
                        help_text="обязательно",
                        max_length=255,
                        verbose_name="сроки доставки",
                    ),
                ),
                (
                    "delivery_window",
                    models.CharField(
                        help_text="обязательно",
                        max_length=255,
                        verbose_name="временное окно доставки",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="обязательно", verbose_name="Список заказа"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Опция доставки",
                "verbose_name_plural": "Опции доставок",
            },
        ),
        migrations.CreateModel(
            name="PaymentSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="обязательно", max_length=255, verbose_name="название"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Вариант оплаты",
                "verbose_name_plural": "Варианты платежей",
            },
        ),
    ]
