# Generated by Django 4.1.1 on 2022-09-26 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="* обязательно уникальное название",
                        max_length=255,
                        verbose_name="название",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalogue.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категорииPcate",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Обязательное поле",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="необязательно", verbose_name="описание"
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_lenght": "Цена должна быть в диапазоне от 0 до 999.99 грн"
                            }
                        },
                        help_text="max 99999.99 грн",
                        max_digits=7,
                        verbose_name="стандартная цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="выберите доступность продукта",
                        verbose_name="доступность продукта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлен"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalogue.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="бренд")),
            ],
            options={
                "verbose_name": "бренд",
                "verbose_name_plural": "бренды",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecific",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное поле",
                        max_length=255,
                        verbose_name="Название характеристики типа товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спецификафия товара",
                "verbose_name_plural": "Спецификафии товаров",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="Тип товара",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Тип продукта",
                "verbose_name_plural": "Типы продуктов",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecificValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=100, verbose_name="описание характеристик"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalogue.productspecific",
                        verbose_name="выберите из списка",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "описание характеристик товара",
            },
        ),
        migrations.AddField(
            model_name="productspecific",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="catalogue.producttype"
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название",
                        max_length=100,
                        verbose_name="название",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="добавьте изображение товара",
                        upload_to="images/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="введите альтернативный текст",
                        max_length=150,
                        null=True,
                        verbose_name="альтернативный текст",
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "изображения товара",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalogue.productbrand",
                verbose_name="бренд",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalogue.producttype",
                verbose_name="Тип товара",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="users_wishlist",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
